# Generated by Django 2.0.4 on 2018-05-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuariopropietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarioganado',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
