# Generated by Django 2.0.4 on 2018-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comparacionitermediate_finish_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietarioganado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
